"""
EBM training on toxic vs. clean labels.
Uses contrastive margin loss to separate clean (low energy) and toxic (high energy) states.
"""

import torch
import torch.nn as nn
import numpy as np
import os
from v7_engine.ebm.energy_model import EnergyModel
from v7_engine.config import SDE_LATENT_DIM, EBM_EPOCHS, EBM_BATCH_SIZE, EBM_LR, CHECKPOINT_EBM

def train_ebm(
    x_clean: np.ndarray,   # (N_clean, latent_dim)
    x_toxic: np.ndarray,   # (N_toxic, latent_dim)
    epochs: int = EBM_EPOCHS,
    batch_size: int = EBM_BATCH_SIZE,
    lr: float = EBM_LR,
    save_path: str = CHECKPOINT_EBM
) -> EnergyModel:
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = EnergyModel().to(device)
    optim = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    
    clean_tensor = torch.tensor(x_clean, dtype=torch.float32).to(device)
    toxic_tensor = torch.tensor(x_toxic, dtype=torch.float32).to(device)
    
    n_clean = len(clean_tensor)
    n_toxic = len(toxic_tensor)
    
    os.makedirs("models", exist_ok=True)
    best_loss = float("inf")
    
    for epoch in range(epochs):
        model.train()
        
        # Shuffle
        idx_clean = torch.randperm(n_clean)
        idx_toxic = torch.randperm(n_toxic)
        
        epoch_loss = 0.0
        n_batches = 0
        
        # Determine number of batches based on the smaller dataset
        iters = min(n_clean, n_toxic) // batch_size
        if iters == 0:
            iters = 1
            batch_size = min(n_clean, n_toxic)
            
        for i in range(iters):
            batch_c = clean_tensor[idx_clean[i*batch_size : (i+1)*batch_size]]
            batch_t = toxic_tensor[idx_toxic[i*batch_size : (i+1)*batch_size]]
            
            e_clean = model(batch_c)
            e_toxic = model(batch_t)
            
            # Standard Noise-Contrastive Estimation (NCE) via BCE
            # e_clean should have low energy (label 0), e_toxic should have high energy (label 1)
            logits = torch.cat([e_clean, e_toxic])
            labels = torch.cat([torch.zeros_like(e_clean), torch.ones_like(e_toxic)])
            loss = torch.nn.functional.binary_cross_entropy_with_logits(logits, labels)
            
            optim.zero_grad()
            loss.backward()
            optim.step()
            
            epoch_loss += loss.item()
            n_batches += 1
            
        avg_loss = epoch_loss / n_batches
        if epoch % 10 == 0:
            print(f"EBM Epoch {epoch} | Loss: {avg_loss:.4f}")
            
        if avg_loss < best_loss:
            best_loss = avg_loss
            if save_path:
                os.makedirs(os.path.dirname(save_path), exist_ok=True)
                torch.save(model.state_dict(), save_path)
            
    return model


def main():
    """
    Production training entrypoint.
    Loads x_clean / x_toxic from dataset files generated by generate_ebm_dataset.py.
    Falls back to an error if dataset files don't exist — never trains on random noise.
    """
    from v7_engine.config import MODELS_DIR, CHECKPOINT_EBM
    import os
    clean_path = os.path.join(MODELS_DIR, "ebm_clean.npy")
    toxic_path = os.path.join(MODELS_DIR, "ebm_toxic.npy")

    if not os.path.exists(clean_path) or not os.path.exists(toxic_path):
        raise FileNotFoundError(
            f"EBM dataset not found. Run first:\n"
            f"  python -m v7_engine.training.generate_ebm_dataset\n"
            f"Expected files: {clean_path}, {toxic_path}"
        )

    x_clean = np.load(clean_path)
    x_toxic = np.load(toxic_path)
    print(f"Loaded EBM dataset: {len(x_clean)} clean, {len(x_toxic)} toxic samples")

    model = train_ebm(
        x_clean    = x_clean,
        x_toxic    = x_toxic,
        epochs     = EBM_EPOCHS,
        batch_size = EBM_BATCH_SIZE,
        lr         = EBM_LR,
    )
    print(f"EBM training complete. Best model saved to {CHECKPOINT_EBM}")
    return model


if __name__ == "__main__":
    main()
